### PR TITLE
Fix the "Not Working for both fans" by calling "setFanSpeed()" two times

### PR DESCRIPTION
**Pull request by kagaminehaku**
fastest and simplest ways to fix

### CODE REVIEW

**Comment by Karmel0x** [comment]
#20

**Comment by kagaminehaku** [comment]
so i should close it right:D?

**Comment by Karmel0x** [comment]
would be nice if you can confirm if it's working properly in latest release

**Comment by JacobGroover** [comment]
> would be nice if you can confirm if it's working properly in latest release

I can confirm it's working on my ROG Zephyrus G15. Just want to also leave a shoutout and thanks to you here. 

EDIT: The GUI is pretty jerky/somewhat unresponsive when the Auto Refresh Stats Advanced option is turned on. Doesn't seem to be creating any extra cpu or memory footprint under those conditions, maybe a result of single threading? I haven't dug into the code thoroughly yet, will check back later and let you know what I find.

Had to take a Respondus Lockdown Browser quiz on campus last night and my fans went crazy with CPU spiking to 100% ever since I finished it. Finally figured out from Windows Event Viewer it broke something with .NET framework and caused ArmouryCrate to crash and attempt to restart repeatedly, capping my CPU. Have a software dev project due at midnight and was unable to even type in my IDE trying to make unit tests with the cpu capped. Reinstalling .NET and uninstalling Armoury Crate fixed it, except then my fans were off so laptop was overheating. You saved me my friend. (Yes, we are friends now)

**Pull request closed without merging**
